### ISSUE TITLE
NODE_ENV: production causes the UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by akaNightmare** [Davide-Gheri/nestjs-mercurius#222]
Hello,

while adding `NODE_ENV: production` to docker container NestJS with Mercurius module causes an error, here a stacktrace
```

2021-08-19T09:33:10.167166200Z [Nest] 51  - 08/19/2021, 9:33:10 AM     LOG [NestFactory] Starting Nest application...
2021-08-19T09:33:10.290469700Z [Nest] 51  - 08/19/2021, 9:33:10 AM    WARN [HttpService] DEPRECATED! "HttpModule" (from the "@nestjs/common" package) is deprecated and will be removed in the next major release. Please, use the "@nestjs/axios" package instead.
2021-08-19T09:33:10.308618100Z [Nest] 51  - 08/19/2021, 9:33:10 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +18ms
2021-08-19T09:33:10.308947400Z [Nest] 51  - 08/19/2021, 9:33:10 AM     LOG [InstanceLoader] SentryModule dependencies initialized +1ms
2021-08-19T09:33:10.309330500Z [Nest] 51  - 08/19/2021, 9:33:10 AM     LOG [InstanceLoader] GeocoderModule dependencies initialized +0ms
2021-08-19T09:33:10.309753200Z [Nest] 51  - 08/19/2021, 9:33:10 AM     LOG [InstanceLoader] MailerModule dependencies initialized +1ms
2021-08-19T09:33:10.310271400Z [Nest] 51  - 08/19/2021, 9:33:10 AM     LOG [InstanceLoader] PaginatorModule dependencies initialized +0ms
2021-08-19T09:33:10.310588900Z [Nest] 51  - 08/19/2021, 9:33:10 AM     LOG [InstanceLoader] MailerModule dependencies initialized +0ms
2021-08-19T09:33:10.311131100Z [Nest] 51  - 08/19/2021, 9:33:10 AM     LOG [InstanceLoader] TimezoneModule dependencies initialized +1ms
2021-08-19T09:33:10.314556100Z [Nest] 51  - 08/19/2021, 9:33:10 AM     LOG [InstanceLoader] HttpModule dependencies initialized +3ms
2021-08-19T09:33:10.315266100Z [Nest] 51  - 08/19/2021, 9:33:10 AM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +1ms
2021-08-19T09:33:10.315561700Z [Nest] 51  - 08/19/2021, 9:33:10 AM     LOG [InstanceLoader] AwsSdkModule dependencies initialized +0ms
2021-08-19T09:33:10.316444900Z [Nest] 51  - 08/19/2021, 9:33:10 AM     LOG [InstanceLoader] DiscoveryModule dependencies initialized +0ms
2021-08-19T09:33:10.316809200Z [Nest] 51  - 08/19/2021, 9:33:10 AM     LOG [InstanceLoader] MercuriusCoreModule dependencies initialized +1ms
2021-08-19T09:33:10.317670500Z [Nest] 51  - 08/19/2021, 9:33:10 AM     LOG [InstanceLoader] TerminusModule dependencies initialized +1ms
2021-08-19T09:33:10.318316800Z [Nest] 51  - 08/19/2021, 9:33:10 AM     LOG [InstanceLoader] ConfigModule dependencies initialized +0ms
2021-08-19T09:33:10.318778400Z [Nest] 51  - 08/19/2021, 9:33:10 AM     LOG [InstanceLoader] ConfigModule dependencies initialized +1ms
2021-08-19T09:33:10.319047500Z [Nest] 51  - 08/19/2021, 9:33:10 AM     LOG [InstanceLoader] S3ManagerModule dependencies initialized +0ms
2021-08-19T09:33:10.331650800Z [Nest] 51  - 08/19/2021, 9:33:10 AM     LOG [InstanceLoader] EventEmitterModule dependencies initialized +12ms
2021-08-19T09:33:10.364046700Z [Nest] 51  - 08/19/2021, 9:33:10 AM     LOG [InstanceLoader] SentryCoreModule dependencies initialized +33ms
2021-08-19T09:33:10.364356000Z [Nest] 51  - 08/19/2021, 9:33:10 AM     LOG [InstanceLoader] GeocoderCoreModule dependencies initialized +0ms
2021-08-19T09:33:10.364753100Z [Nest] 51  - 08/19/2021, 9:33:10 AM     LOG [InstanceLoader] MailerCoreModule dependencies initialized +1ms
2021-08-19T09:33:10.364937100Z [Nest] 51  - 08/19/2021, 9:33:10 AM     LOG [InstanceLoader] JwtModule dependencies initialized +0ms
2021-08-19T09:33:10.365598600Z [Nest] 51  - 08/19/2021, 9:33:10 AM     LOG [InstanceLoader] GraphQLSchemaBuilderModule dependencies initialized +1ms
2021-08-19T09:33:10.366691200Z [Nest] 51  - 08/19/2021, 9:33:10 AM     LOG [InstanceLoader] MercuriusModule dependencies initialized +1ms
2021-08-19T09:33:10.880305100Z [Nest] 51  - 08/19/2021, 9:33:10 AM     LOG [InstanceLoader] TypeOrmCoreModule dependencies initialized +513ms
2021-08-19T09:33:10.880968500Z [Nest] 51  - 08/19/2021, 9:33:10 AM     LOG [InstanceLoader] RelationLoaderModule dependencies initialized +1ms
2021-08-19T09:33:10.881226300Z [Nest] 51  - 08/19/2021, 9:33:10 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
2021-08-19T09:33:10.881711000Z [Nest] 51  - 08/19/2021, 9:33:10 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +1ms
2021-08-19T09:33:10.881730600Z [Nest] 51  - 08/19/2021, 9:33:10 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
2021-08-19T09:33:10.881991300Z [Nest] 51  - 08/19/2021, 9:33:10 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
2021-08-19T09:33:10.882350300Z [Nest] 51  - 08/19/2021, 9:33:10 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
2021-08-19T09:33:10.882582100Z [Nest] 51  - 08/19/2021, 9:33:10 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +1ms
2021-08-19T09:33:10.882789500Z [Nest] 51  - 08/19/2021, 9:33:10 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
2021-08-19T09:33:10.883074100Z [Nest] 51  - 08/19/2021, 9:33:10 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
2021-08-19T09:33:10.883345400Z [Nest] 51  - 08/19/2021, 9:33:10 AM     LOG [InstanceLoader] ExportModule dependencies initialized +0ms
2021-08-19T09:33:10.890401300Z [Nest] 51  - 08/19/2021, 9:33:10 AM     LOG [InstanceLoader] StateModule dependencies initialized +7ms
2021-08-19T09:33:10.890933600Z [Nest] 51  - 08/19/2021, 9:33:10 AM     LOG [InstanceLoader] AddressModule dependencies initialized +1ms
2021-08-19T09:33:10.892074100Z [Nest] 51  - 08/19/2021, 9:33:10 AM     LOG [InstanceLoader] ReferenceDataModule dependencies initialized +1ms
2021-08-19T09:33:10.892311200Z [Nest] 51  - 08/19/2021, 9:33:10 AM     LOG [InstanceLoader] AppModule dependencies initialized +0ms
2021-08-19T09:33:10.893340900Z [Nest] 51  - 08/19/2021, 9:33:10 AM     LOG [InstanceLoader] ReferralListModule dependencies initialized +1ms
2021-08-19T09:33:10.893563900Z [Nest] 51  - 08/19/2021, 9:33:10 AM     LOG [InstanceLoader] OrganizationModule dependencies initialized +1ms
2021-08-19T09:33:10.895690000Z [Nest] 51  - 08/19/2021, 9:33:10 AM     LOG [InstanceLoader] UserModule dependencies initialized +0ms
2021-08-19T09:33:10.895763900Z [Nest] 51  - 08/19/2021, 9:33:10 AM     LOG [InstanceLoader] AuthModule dependencies initialized +1ms
2021-08-19T09:33:10.895791200Z [Nest] 51  - 08/19/2021, 9:33:10 AM     LOG [InstanceLoader] ProviderModule dependencies initialized +0ms
2021-08-19T09:33:10.895816100Z [Nest] 51  - 08/19/2021, 9:33:10 AM     LOG [InstanceLoader] InvitationModule dependencies initialized +1ms
2021-08-19T09:33:10.938682900Z [Nest] 51  - 08/19/2021, 9:33:10 AM     LOG [RoutesResolver] AppController {/}: +42ms
    2021-08-19T09:33:10.948952600Z [Nest] 51  - 08/19/2021, 9:33:10 AM     LOG [RouterExplorer] Mapped {/ping, GET} route +11ms
        2021-08-19T09:33:10.951546300Z [Nest] 51  - 08/19/2021, 9:33:10 AM     LOG [RouterExplorer] Mapped {/info, GET} route +2ms
            2021-08-19T09:33:10.954265700Z [Nest] 51  - 08/19/2021, 9:33:10 AM     LOG [RouterExplorer] Mapped {/healthcheck, GET} route +3ms
                2021-08-19T09:33:10.954647600Z [Nest] 51  - 08/19/2021, 9:33:10 AM     LOG [RoutesResolver] ExportExcelController {/export/excel}: +0ms
                2021-08-19T09:33:10.957700800Z [Nest] 51  - 08/19/2021, 9:33:10 AM     LOG [RouterExplorer] Mapped {/export/excel/:entity, GET} route +3ms
                2021-08-19T09:33:10.958044800Z [Nest] 51  - 08/19/2021, 9:33:10 AM     LOG [RoutesResolver] SampleController {/}: +1ms
                    2021-08-19T09:33:10.960809700Z [Nest] 51  - 08/19/2021, 9:33:10 AM     LOG [RouterExplorer] Mapped {/sample/invitation, GET} route +3ms
                    2021-08-19T09:33:11.323526200Z (node:51) UnhandledPromiseRejectionWarning: FastifyError: Invalid options: Cannot find type User
                    2021-08-19T09:33:11.323568900Z     at AsyncFunction.fastifyGraphQl.defineResolvers (/srv/api/node_modules/mercurius/index.js:344:15)
                    2021-08-19T09:33:11.323587600Z     at AsyncFunction.fastifyGraphQl.defineLoaders (/srv/api/node_modules/mercurius/index.js:396:20)
                    2021-08-19T09:33:11.323611500Z     at fp.name (/srv/api/node_modules/mercurius/index.js:414:20)
                    2021-08-19T09:33:11.323633300Z     at Plugin.exec (/srv/api/node_modules/avvio/plugin.js:132:19)
                    2021-08-19T09:33:11.323655600Z     at Boot.loadPlugin (/srv/api/node_modules/avvio/plugin.js:267:10)
                    2021-08-19T09:33:11.323677900Z     at release (/srv/api/node_modules/fastq/queue.js:149:16)
                    2021-08-19T09:33:11.323701300Z     at Object.resume (/srv/api/node_modules/fastq/queue.js:82:7)
                    2021-08-19T09:33:11.323724600Z     at setup (/srv/api/node_modules/avvio/plugin.js:164:12)
                    2021-08-19T09:33:11.323747900Z     at Plugin.loadedSoFar (/srv/api/node_modules/avvio/plugin.js:176:7)
                    2021-08-19T09:33:11.323771000Z     at Boot._loadRegistered (/srv/api/node_modules/avvio/boot.js:227:17)
                    2021-08-19T09:33:11.323794100Z     at Object.<anonymous> (/srv/api/node_modules/avvio/boot.js:390:20)
                        2021-08-19T09:33:11.323813300Z     at processTicksAndRejections (internal/process/task_queues.js:95:5)
                        2021-08-19T09:33:11.323835000Z (Use `node --trace-warnings ...` to show where the warning was created)
                        2021-08-19T09:33:11.323856900Z (node:51) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
                        2021-08-19T09:33:11.323880400Z (node:51) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

and as you can see 
`2021-08-19T09:33:10.316809200Z [Nest] 51  - 08/19/2021, 9:33:10 AM     LOG [InstanceLoader] MercuriusCoreModule dependencies initialized +1ms` loaded too, without `NODE_ENV: production` everything is fine and the app starts as expected.

Thanks in advance.

**Comment by akaNightmare** [comment]
actually it's not working for all NODE_ENV vars except `development`

**Comment by akaNightmare** [comment]
my fault, need to set `true` or path to `schema.graphql` for `autoSchemaFile` property
